import type {
  Incident,
  ResponseTeam,
  Hospital,
  Notification,
  User,
  EmergencyType,
  Severity,
  IncidentStatus,
  TeamType,
  TeamStatus,
  HospitalStatus,
} from './types';

export const currentUser: User = {
  id: 'U-001',
  name: 'Aarav Sharma',
  email: 'aarav.sharma@ers.gov',
  role: 'Emergency Dispatcher',
  avatar: null,
};

export const emergencyTypes: EmergencyType[] = [
  'Vehicle Accident',
  'Fire',
  'Medical Emergency',
  'Road Accident',
  'Other',
];

export const severities: Severity[] = ['Critical', 'High', 'Medium', 'Low'];

export const incidentStatuses: IncidentStatus[] = [
  'Detected',
  'Pending Response',
  'Team Dispatched',
  'On the Way',
  'Under Response',
  'Resolved',
];

export const teamTypes: TeamType[] = [
  'Ambulance',
  'Police',
  'Fire & Rescue',
  'Medical Response',
];

export const teamStatuses: TeamStatus[] = ['Available', 'Dispatched', 'Busy', 'Offline'];

export const hospitalStatuses: HospitalStatus[] = [
  'Available',
  'Limited Capacity',
  'Full',
];

const now = Date.now();
const minsAgo = (m: number) => new Date(now - m * 60 * 1000).toISOString();

export const mockIncidents: Incident[] = [
  {
    id: 'ER-1024',
    type: 'Vehicle Accident',
    severity: 'Critical',
    description:
      'Multi-vehicle collision on the highway overpass. Two cars and a delivery truck involved. Several passengers trapped.',
    location: 'NH-48 Overpass, Sector 21',
    coordinates: { lat: 28.4917, lng: 77.0873 },
    reportedTime: minsAgo(12),
    affectedPeople: 5,
    reporterName: 'Rohan Mehta',
    reporterContact: '+91 98765 43210',
    status: 'Team Dispatched',
    assignedTeamId: 'RT-01',
    hospitalId: 'H-01',
    timeline: [
      { id: 't1', label: 'Emergency detected', timestamp: minsAgo(12), done: true },
      { id: 't2', label: 'Alert received', timestamp: minsAgo(11), done: true },
      { id: 't3', label: 'Response team assigned', timestamp: minsAgo(10), done: true },
      { id: 't4', label: 'Team dispatched', timestamp: minsAgo(8), done: true },
      { id: 't5', label: 'Team reached location', timestamp: minsAgo(0), done: false },
      { id: 't6', label: 'Patient transferred', timestamp: '', done: false },
      { id: 't7', label: 'Incident resolved', timestamp: '', done: false },
    ],
  },
  {
    id: 'ER-1023',
    type: 'Fire',
    severity: 'High',
    description:
      'Fire reported in a commercial warehouse. Smoke visible from adjacent buildings. Firefighters requested.',
    location: 'Industrial Area, Phase 2',
    coordinates: { lat: 28.5039, lng: 77.0952 },
    reportedTime: minsAgo(28),
    affectedPeople: 0,
    reporterName: 'Priya Nair',
    reporterContact: '+91 99887 76655',
    status: 'On the Way',
    assignedTeamId: 'RT-05',
    hospitalId: null,
    timeline: [
      { id: 't1', label: 'Emergency detected', timestamp: minsAgo(28), done: true },
      { id: 't2', label: 'Alert received', timestamp: minsAgo(27), done: true },
      { id: 't3', label: 'Response team assigned', timestamp: minsAgo(25), done: true },
      { id: 't4', label: 'Team dispatched', timestamp: minsAgo(23), done: true },
      { id: 't5', label: 'Team reached location', timestamp: '', done: false },
      { id: 't6', label: 'Patient transferred', timestamp: '', done: false },
      { id: 't7', label: 'Incident resolved', timestamp: '', done: false },
    ],
  },
  {
    id: 'ER-1022',
    type: 'Medical Emergency',
    severity: 'High',
    description:
      'Elderly male experiencing chest pain and shortness of breath at a residential complex. Ambulance requested.',
    location: 'Greenwood Residency, Block C',
    coordinates: { lat: 28.4772, lng: 77.0534 },
    reportedTime: minsAgo(45),
    affectedPeople: 1,
    reporterName: 'Sunita Rao',
    reporterContact: '+91 90909 80808',
    status: 'Under Response',
    assignedTeamId: 'RT-02',
    hospitalId: 'H-02',
    timeline: [
      { id: 't1', label: 'Emergency detected', timestamp: minsAgo(45), done: true },
      { id: 't2', label: 'Alert received', timestamp: minsAgo(44), done: true },
      { id: 't3', label: 'Response team assigned', timestamp: minsAgo(42), done: true },
      { id: 't4', label: 'Team dispatched', timestamp: minsAgo(40), done: true },
      { id: 't5', label: 'Team reached location', timestamp: minsAgo(20), done: true },
      { id: 't6', label: 'Patient transferred', timestamp: minsAgo(5), done: true },
      { id: 't7', label: 'Incident resolved', timestamp: '', done: false },
    ],
  },
  {
    id: 'ER-1021',
    type: 'Road Accident',
    severity: 'Medium',
    description:
      'Two-wheeler skid on wet road. Rider has minor injuries and is conscious. Traffic building up.',
    location: 'MG Road, near Metro Station',
    coordinates: { lat: 28.4792, lng: 77.0905 },
    reportedTime: minsAgo(95),
    affectedPeople: 1,
    reporterName: 'Kabir Singh',
    reporterContact: '+91 91234 56780',
    status: 'Resolved',
    assignedTeamId: 'RT-03',
    hospitalId: 'H-03',
    timeline: [
      { id: 't1', label: 'Emergency detected', timestamp: minsAgo(95), done: true },
      { id: 't2', label: 'Alert received', timestamp: minsAgo(94), done: true },
      { id: 't3', label: 'Response team assigned', timestamp: minsAgo(92), done: true },
      { id: 't4', label: 'Team dispatched', timestamp: minsAgo(90), done: true },
      { id: 't5', label: 'Team reached location', timestamp: minsAgo(70), done: true },
      { id: 't6', label: 'Patient transferred', timestamp: minsAgo(55), done: true },
      { id: 't7', label: 'Incident resolved', timestamp: minsAgo(40), done: true },
    ],
  },
  {
    id: 'ER-1020',
    type: 'Other',
    severity: 'Low',
    description:
      'Fallen tree blocking a side road. No injuries reported. Clearance team requested.',
    location: 'Palm Avenue, Sector 12',
    coordinates: { lat: 28.4651, lng: 77.0432 },
    reportedTime: minsAgo(140),
    affectedPeople: 0,
    reporterName: 'Anita Verma',
    reporterContact: '+91 95555 44433',
    status: 'Resolved',
    assignedTeamId: 'RT-04',
    hospitalId: null,
    timeline: [
      { id: 't1', label: 'Emergency detected', timestamp: minsAgo(140), done: true },
      { id: 't2', label: 'Alert received', timestamp: minsAgo(139), done: true },
      { id: 't3', label: 'Response team assigned', timestamp: minsAgo(137), done: true },
      { id: 't4', label: 'Team dispatched', timestamp: minsAgo(135), done: true },
      { id: 't5', label: 'Team reached location', timestamp: minsAgo(115), done: true },
      { id: 't6', label: 'Patient transferred', timestamp: '', done: false },
      { id: 't7', label: 'Incident resolved', timestamp: minsAgo(100), done: true },
    ],
  },
  {
    id: 'ER-1019',
    type: 'Medical Emergency',
    severity: 'Critical',
    description:
      'Pregnant woman in active labor at a shopping mall. Medical response team dispatched.',
    location: 'Central Mall, Food Court',
    coordinates: { lat: 28.4825, lng: 77.0612 },
    reportedTime: minsAgo(160),
    affectedPeople: 1,
    reporterName: 'Mall Security',
    reporterContact: '+91 90000 12345',
    status: 'Resolved',
    assignedTeamId: 'RT-02',
    hospitalId: 'H-02',
    timeline: [
      { id: 't1', label: 'Emergency detected', timestamp: minsAgo(160), done: true },
      { id: 't2', label: 'Alert received', timestamp: minsAgo(159), done: true },
      { id: 't3', label: 'Response team assigned', timestamp: minsAgo(157), done: true },
      { id: 't4', label: 'Team dispatched', timestamp: minsAgo(155), done: true },
      { id: 't5', label: 'Team reached location', timestamp: minsAgo(140), done: true },
      { id: 't6', label: 'Patient transferred', timestamp: minsAgo(125), done: true },
      { id: 't7', label: 'Incident resolved', timestamp: minsAgo(110), done: true },
    ],
  },
];

export const mockResponseTeams: ResponseTeam[] = [
  {
    id: 'RT-01',
    type: 'Ambulance',
    members: 4,
    vehicle: 'Ambulance A-101',
    location: 'Highway Rescue Base, Sector 21',
    coordinates: { lat: 28.492, lng: 77.088 },
    status: 'Dispatched',
    currentIncidentId: 'ER-1024',
  },
  {
    id: 'RT-02',
    type: 'Medical Response',
    members: 3,
    vehicle: 'Rapid Medical Van M-204',
    location: 'City Medical Center',
    coordinates: { lat: 28.4775, lng: 77.054 },
    status: 'Busy',
    currentIncidentId: 'ER-1022',
  },
  {
    id: 'RT-03',
    type: 'Ambulance',
    members: 4,
    vehicle: 'Ambulance A-108',
    location: 'Central Depot',
    coordinates: { lat: 28.4795, lng: 77.091 },
    status: 'Available',
    currentIncidentId: null,
  },
  {
    id: 'RT-04',
    type: 'Police',
    members: 6,
    vehicle: 'Patrol Cruiser P-014',
    location: 'Sector 12 Police Outpost',
    coordinates: { lat: 28.465, lng: 77.043 },
    status: 'Available',
    currentIncidentId: null,
  },
  {
    id: 'RT-05',
    type: 'Fire & Rescue',
    members: 8,
    vehicle: 'Fire Engine F-003',
    location: 'Industrial Fire Station',
    coordinates: { lat: 28.504, lng: 77.095 },
    status: 'Dispatched',
    currentIncidentId: 'ER-1023',
  },
  {
    id: 'RT-06',
    type: 'Fire & Rescue',
    members: 8,
    vehicle: 'Fire Engine F-007',
    location: 'Industrial Fire Station',
    coordinates: { lat: 28.5045, lng: 77.0955 },
    status: 'Available',
    currentIncidentId: null,
  },
  {
    id: 'RT-07',
    type: 'Police',
    members: 4,
    vehicle: 'Patrol Cruiser P-021',
    location: 'MG Road Checkpost',
    coordinates: { lat: 28.479, lng: 77.0908 },
    status: 'Offline',
    currentIncidentId: null,
  },
  {
    id: 'RT-08',
    type: 'Medical Response',
    members: 3,
    vehicle: 'Rapid Medical Van M-211',
    location: 'South City Clinic',
    coordinates: { lat: 28.46, lng: 77.05 },
    status: 'Available',
    currentIncidentId: null,
  },
];

export const mockHospitals: Hospital[] = [
  {
    id: 'H-01',
    name: 'Apex Multispecialty Hospital',
    location: 'Sector 21, Highway Link Road',
    coordinates: { lat: 28.4925, lng: 77.0885 },
    emergencyDept: true,
    availableBeds: 14,
    icuBeds: 3,
    ambulanceAvailable: 2,
    distanceFromIncident: 1.2,
    status: 'Available',
  },
  {
    id: 'H-02',
    name: 'City Medical Center',
    location: 'Greenwood Avenue, Block C',
    coordinates: { lat: 28.4778, lng: 77.0538 },
    emergencyDept: true,
    availableBeds: 6,
    icuBeds: 1,
    ambulanceAvailable: 1,
    distanceFromIncident: 2.8,
    status: 'Limited Capacity',
  },
  {
    id: 'H-03',
    name: 'Metro General Hospital',
    location: 'MG Road, near Metro Station',
    coordinates: { lat: 28.4795, lng: 77.0908 },
    emergencyDept: true,
    availableBeds: 22,
    icuBeds: 5,
    ambulanceAvailable: 3,
    distanceFromIncident: 0.6,
    status: 'Available',
  },
  {
    id: 'H-04',
    name: 'Sunrise Children & Maternity',
    location: 'Central Mall Road',
    coordinates: { lat: 28.4828, lng: 77.0615 },
    emergencyDept: false,
    availableBeds: 9,
    icuBeds: 2,
    ambulanceAvailable: 1,
    distanceFromIncident: 3.4,
    status: 'Limited Capacity',
  },
  {
    id: 'H-05',
    name: 'Lifeline Trauma Center',
    location: 'Industrial Area, Phase 2',
    coordinates: { lat: 28.5042, lng: 77.0955 },
    emergencyDept: true,
    availableBeds: 0,
    icuBeds: 0,
    ambulanceAvailable: 0,
    distanceFromIncident: 0.4,
    status: 'Full',
  },
  {
    id: 'H-06',
    name: 'South City Hospital',
    location: 'Palm Avenue, Sector 12',
    coordinates: { lat: 28.4653, lng: 77.0435 },
    emergencyDept: true,
    availableBeds: 18,
    icuBeds: 4,
    ambulanceAvailable: 2,
    distanceFromIncident: 5.1,
    status: 'Available',
  },
];

export const mockNotifications: Notification[] = [
  {
    id: 'N-001',
    type: 'critical',
    title: 'Critical vehicle accident detected',
    message: 'Incident #ER-1024 reported on NH-48 Overpass, Sector 21.',
    timestamp: minsAgo(12),
    read: false,
  },
  {
    id: 'N-002',
    type: 'dispatch',
    title: 'Ambulance dispatched',
    message: 'Ambulance RT-01 dispatched to Incident #ER-1024.',
    timestamp: minsAgo(8),
    read: false,
  },
  {
    id: 'N-003',
    type: 'update',
    title: 'Hospital capacity updated',
    message: 'Lifeline Trauma Center is now at full capacity.',
    timestamp: minsAgo(30),
    read: false,
  },
  {
    id: 'N-004',
    type: 'update',
    title: 'Response team has reached the incident',
    message: 'Medical Response RT-02 reached Incident #ER-1022.',
    timestamp: minsAgo(20),
    read: true,
  },
  {
    id: 'N-005',
    type: 'resolve',
    title: 'Incident resolved',
    message: 'Incident #ER-1021 marked as resolved.',
    timestamp: minsAgo(40),
    read: true,
  },
];

export const emergenciesByDay = [
  { day: 'Mon', emergencies: 8, resolved: 6 },
  { day: 'Tue', emergencies: 12, resolved: 10 },
  { day: 'Wed', emergencies: 7, resolved: 7 },
  { day: 'Thu', emergencies: 15, resolved: 11 },
  { day: 'Fri', emergencies: 18, resolved: 14 },
  { day: 'Sat', emergencies: 11, resolved: 9 },
  { day: 'Sun', emergencies: 6, resolved: 5 },
];

export const emergencyTypeDistribution = [
  { name: 'Vehicle Accident', value: 32, color: 'hsl(var(--chart-1))' },
  { name: 'Medical Emergency', value: 28, color: 'hsl(var(--chart-2))' },
  { name: 'Fire', value: 18, color: 'hsl(var(--chart-3))' },
  { name: 'Road Accident', value: 14, color: 'hsl(var(--chart-4))' },
  { name: 'Other', value: 8, color: 'hsl(var(--chart-5))' },
];

export const severityDistribution = [
  { name: 'Critical', value: 12, color: 'hsl(0 84% 60%)' },
  { name: 'High', value: 24, color: 'hsl(25 95% 53%)' },
  { name: 'Medium', value: 38, color: 'hsl(38 92% 50%)' },
  { name: 'Low', value: 26, color: 'hsl(142 71% 45%)' },
];
